<?php

namespace Modules\Core\Http\Controllers;

use Illuminate\Http\Response;
use Modules\Core\Entities\SystemSetting;
use Modules\Core\Support\ColorUtil;

/**
 * Parity with webinocrm class-white-label.php:
 *   - `apply_color_scheme()` → emits CSS variables, button overrides, RGB helpers
 *   - `add_custom_css()` / `add_custom_admin_css()` → appended custom CSS
 *
 * Public endpoint `/api/v1/core/branding.css` returns the theme CSS that the frontend `<link>`s
 * to apply runtime white-label branding without rebuilding the Next.js app.
 */
class BrandingController extends Controller
{
    private const CACHE_KEY = 'core:branding.css';

    private const DEFAULTS = [
        'primary_color' => '#4CAF50',
        'secondary_color' => '#2196F3',
        'accent_color' => '#FF5722',
        'success_color' => '#28a745',
        'warning_color' => '#ffc107',
        'danger_color' => '#dc3545',
        'info_color' => '#17a2b8',
        'font_family' => 'Vazirmatn, system-ui, sans-serif',
        'font_size' => '14px',
        'border_radius' => '0.5rem',
        'custom_css' => '',
        'brand_logo_url' => '',
    ];

    public function css(): Response
    {
        $etag = md5('v1:'.((string) SystemSetting::query()->where('group', 'branding')->max('updated_at')));
        $css = cache()->remember(self::CACHE_KEY.':'.$etag, now()->addMinutes(15), fn () => $this->compile());

        return response($css, 200, [
            'Content-Type' => 'text/css; charset=utf-8',
            'Cache-Control' => 'public, max-age=60, s-maxage=300, stale-while-revalidate=60',
            'ETag' => '"'.$etag.'"',
        ]);
    }

    private function compile(): string
    {
        $vals = $this->values();
        $primary = ColorUtil::normalizeHex($vals['primary_color']);
        $secondary = ColorUtil::normalizeHex($vals['secondary_color']);
        $accent = ColorUtil::normalizeHex($vals['accent_color']);
        $success = ColorUtil::normalizeHex($vals['success_color']);
        $warning = ColorUtil::normalizeHex($vals['warning_color']);
        $danger = ColorUtil::normalizeHex($vals['danger_color']);
        $info = ColorUtil::normalizeHex($vals['info_color']);

        $primaryRgb = ColorUtil::hexToRgb($primary);
        $secondaryRgb = ColorUtil::hexToRgb($secondary);
        $darken10 = ColorUtil::darken($primary, 10);
        $darken15 = ColorUtil::darken($primary, 15);

        $custom = trim((string) ($vals['custom_css'] ?? ''));
        $custom = strip_tags($custom);

        return <<<CSS
/* Generated by Webino BrandingController — parity with webinocrm class-white-label.php */
:root {
    --webino-primary-color: {$primary};
    --webino-primary-rgb: {$primaryRgb};
    --webino-primary-darker: {$darken10};
    --webino-secondary-color: {$secondary};
    --webino-secondary-rgb: {$secondaryRgb};
    --webino-accent-color: {$accent};
    --webino-success-color: {$success};
    --webino-warning-color: {$warning};
    --webino-danger-color: {$danger};
    --webino-info-color: {$info};
    --webino-font-family: {$vals['font_family']};
    --webino-font-size: {$vals['font_size']};
    --webino-radius: {$vals['border_radius']};
}

.webino-primary-bg { background-color: {$primary} !important; }
.bg-primary { background-color: {$primary} !important; }
.border-primary { border-color: {$primary} !important; }

.btn-primary, .webino-btn-primary, .webino-button, .webino-button-primary {
    background-color: {$primary} !important;
    border-color: {$primary} !important;
    color: #ffffff !important;
    border-radius: var(--webino-radius);
}
.btn-primary:hover, .btn-primary:focus, .btn-primary:active,
.webino-button:hover, .webino-button:focus, .webino-button:active {
    background-color: {$darken10} !important;
    border-color: {$darken10} !important;
}

.project-card-header,
.profile-header,
.gradient-1 {
    background: linear-gradient(135deg, {$primary} 0%, {$darken15} 100%) !important;
}

.btn-primary-light {
    background-color: rgba({$primaryRgb}, 0.1) !important;
    color: {$primary} !important;
    border-color: rgba({$primaryRgb}, 0.2) !important;
}
.btn-primary-light:hover {
    background-color: {$primary} !important;
    color: #ffffff !important;
}

/* Site font */
body { font-family: var(--webino-font-family); font-size: var(--webino-font-size); }

/* Custom CSS injected from SystemSetting(group=branding) */
{$custom}
CSS;
    }

    /**
     * @return array<string,string>
     */
    private function values(): array
    {
        $stored = SystemSetting::getByGroup('branding');
        $out = self::DEFAULTS;
        foreach ($out as $k => $_) {
            if (array_key_exists($k, $stored) && $stored[$k] !== null && $stored[$k] !== '') {
                $out[$k] = (string) $stored[$k];
            }
        }

        return $out;
    }

    /**
     * Companion JSON endpoint (for SSR/SEO): returns the same values the CSS is built from.
     */
    public function manifest(): \Illuminate\Http\JsonResponse
    {
        return response()->json([
            'data' => $this->values(),
        ]);
    }
}
