<?php

/**
 * Maps API path segments (first segment after /api/v1/{module}/) to Spatie permissions.
 * Used by EnforceModulePermission middleware.
 */
return [
    'core' => [
        'auth' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'config' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'branding' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'manifest.json' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'navigation' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'dashboard' => ['view' => 'core.dashboard.view', 'manage' => 'core.dashboard.view'],
        'settings' => ['view' => 'core.settings.view', 'manage' => 'core.settings.manage'],
        'users' => ['view' => 'core.users.view', 'manage' => 'core.users.manage'],
        'licenses' => ['view' => 'core.licenses.view', 'manage' => 'core.licenses.manage'],
        'logs' => ['view' => 'core.logs.view', 'manage' => 'core.logs.manage'],
        'reports' => ['view' => 'core.dashboard.reports', 'manage' => 'core.dashboard.reports'],
        'maintenance' => ['view' => 'core.settings.manage', 'manage' => 'core.settings.manage'],
        'field-permissions' => ['view' => 'core.settings.manage', 'manage' => 'core.settings.manage'],
        'automation' => ['view' => 'core.settings.view', 'manage' => 'core.settings.manage'],
        'chat' => ['view' => 'core.navigation.view', 'manage' => 'core.navigation.view'],
        'notifications' => ['view' => 'core.notifications.view', 'manage' => 'core.notifications.view'],
        'reminders' => ['view' => 'core.notifications.view', 'manage' => 'core.notifications.view'],
        'activities' => ['view' => 'core.dashboard.view', 'manage' => 'core.dashboard.view'],
        'documents' => ['view' => 'core.dashboard.view', 'manage' => 'core.dashboard.view'],
        'sessions' => ['view' => 'core.users.view', 'manage' => 'core.users.manage'],
        'search' => ['view' => 'core.dashboard.view', 'manage' => 'core.dashboard.view'],
        'analytics' => ['view' => 'core.dashboard.reports', 'manage' => 'core.dashboard.reports'],
        'visitor-stats' => ['view' => 'core.visitor_stats.view', 'manage' => 'core.visitor_stats.view'],
        'canned-responses' => ['view' => 'core.settings.view', 'manage' => 'core.settings.manage'],
        'positions' => ['view' => 'core.settings.view', 'manage' => 'core.settings.manage'],
        'task-categories' => ['view' => 'core.settings.view', 'manage' => 'core.settings.manage'],
        'files' => ['view' => 'core.dashboard.view', 'manage' => 'core.dashboard.view'],
        '*' => ['view' => 'core.navigation.view', 'manage' => 'core.settings.manage'],
    ],
    'crm' => [
        'leads' => ['view' => 'crm.leads.view', 'manage' => 'crm.leads.manage'],
        'accounts' => ['view' => 'crm.accounts.view', 'manage' => 'crm.accounts.manage'],
        'contacts' => ['view' => 'crm.contacts.view', 'manage' => 'crm.contacts.manage'],
        'deals' => ['view' => 'crm.deals.view', 'manage' => 'crm.deals.manage'],
        'pipelines' => ['view' => 'crm.deals.view', 'manage' => 'crm.deals.manage'],
        'sources' => ['view' => 'crm.deals.view', 'manage' => 'crm.deals.manage'],
        'activities' => ['view' => 'crm.deals.view', 'manage' => 'crm.deals.manage'],
        'consultations' => ['view' => 'crm.consultations.view', 'manage' => 'crm.consultations.manage'],
        'statuses' => ['view' => 'crm.leads.view', 'manage' => 'crm.leads.manage'],
        '*' => ['view' => 'crm.leads.view', 'manage' => 'crm.leads.manage'],
    ],
    'hrm' => [
        'staff' => ['view' => 'hrm.staff.view', 'manage' => 'hrm.staff.manage'],
        'employees' => ['view' => 'hrm.staff.view', 'manage' => 'hrm.staff.manage'],
        'attendance' => ['view' => 'hrm.attendance.view', 'manage' => 'hrm.attendance.manage'],
        'leave' => ['view' => 'hrm.leave.view', 'manage' => 'hrm.leave.manage'],
        'payroll' => ['view' => 'hrm.payroll.view', 'manage' => 'hrm.payroll.manage'],
        'recruitment' => ['view' => 'hrm.recruitment.view', 'manage' => 'hrm.recruitment.manage'],
        'performance' => ['view' => 'hrm.performance.view', 'manage' => 'hrm.performance.manage'],
        'training' => ['view' => 'hrm.training.view', 'manage' => 'hrm.training.manage'],
        'org-positions' => ['view' => 'hrm.staff.view', 'manage' => 'hrm.staff.manage'],
        '*' => ['view' => 'hrm.staff.view', 'manage' => 'hrm.staff.manage'],
    ],
    'accounting' => [
        '*' => ['view' => 'accounting.view', 'manage' => 'accounting.manage'],
    ],
    'projects' => [
        'projects' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
        'tasks' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'contracts' => ['view' => 'projects.contracts.view', 'manage' => 'projects.contracts.manage'],
        'tickets' => ['view' => 'projects.tickets.view', 'manage' => 'projects.tickets.manage'],
        'appointments' => ['view' => 'projects.appointments.view', 'manage' => 'projects.appointments.manage'],
        'invoices' => ['view' => 'projects.invoices.view', 'manage' => 'projects.invoices.manage'],
        'time-entries' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'sprints' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'kanban' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'workflow' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'forms' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
        'subscriptions' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
        'products' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
        'task-templates' => ['view' => 'projects.tasks.view', 'manage' => 'projects.tasks.manage'],
        'project-templates' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
        'assignable-users' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.view'],
        '*' => ['view' => 'projects.projects.view', 'manage' => 'projects.projects.manage'],
    ],
    'scm' => [
        '*' => ['view' => 'scm.warehouse.view', 'manage' => 'scm.warehouse.manage'],
    ],
    'sales' => [
        'catalog' => ['view' => 'sales.catalog.view', 'manage' => 'sales.catalog.manage'],
        'campaigns' => ['view' => 'sales.campaigns.view', 'manage' => 'sales.campaigns.manage'],
        'invoices' => ['view' => 'sales.invoices.view', 'manage' => 'sales.invoices.manage'],
        'services' => ['view' => 'sales.catalog.view', 'manage' => 'sales.catalog.manage'],
        '*' => ['view' => 'sales.catalog.view', 'manage' => 'sales.catalog.manage'],
    ],
    'docs' => [
        'contracts' => ['view' => 'docs.contracts.view', 'manage' => 'docs.contracts.manage'],
        'files' => ['view' => 'docs.files.view', 'manage' => 'docs.files.manage'],
        '*' => ['view' => 'docs.contracts.view', 'manage' => 'docs.contracts.manage'],
    ],
    'marketplace' => [
        'products' => ['view' => 'marketplace.products.view', 'manage' => 'marketplace.products.manage'],
        'categories' => ['view' => 'marketplace.products.view', 'manage' => 'marketplace.products.manage'],
        'orders' => ['view' => 'marketplace.products.view', 'manage' => 'marketplace.products.manage'],
        'modules' => ['view' => 'marketplace.modules.view', 'manage' => 'marketplace.modules.manage'],
        'releases' => ['view' => 'marketplace.modules.view', 'manage' => 'marketplace.modules.manage'],
        'gitea' => ['view' => 'marketplace.modules.view', 'manage' => 'marketplace.modules.manage'],
        '*' => ['view' => 'marketplace.products.view', 'manage' => 'marketplace.products.manage'],
    ],
    'integrations' => [
        'modirpayamak' => ['view' => 'integrations.modirpayamak.view', 'manage' => 'integrations.modirpayamak.manage'],
        'sms' => ['view' => 'integrations.sms.manage', 'manage' => 'integrations.sms.manage'],
        'payments' => ['view' => 'integrations.payment.manage', 'manage' => 'integrations.payment.manage'],
        'bale' => ['view' => 'integrations.bale.manage', 'manage' => 'integrations.bale.manage'],
        'telegram' => ['view' => 'integrations.telegram.manage', 'manage' => 'integrations.telegram.manage'],
        '*' => ['view' => 'integrations.sms.manage', 'manage' => 'integrations.sms.manage'],
    ],
    'mfg' => [
        'boms' => ['view' => 'mfg.boms.view', 'manage' => 'mfg.boms.manage'],
        'work-orders' => ['view' => 'mfg.work_orders.view', 'manage' => 'mfg.work_orders.manage'],
        'inspections' => ['view' => 'mfg.quality.view', 'manage' => 'mfg.quality.manage'],
        'planning' => ['view' => 'mfg.planning.view', 'manage' => 'mfg.planning.view'],
        'overview' => ['view' => 'mfg.boms.view', 'manage' => 'mfg.boms.view'],
        '*' => ['view' => 'mfg.boms.view', 'manage' => 'mfg.boms.manage'],
    ],
    'site_builder' => [
        'catalog' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
        'categories' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
        'types' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
        'features' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
        'packages' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
        'provisions' => ['view' => 'site_builder.provision.view', 'manage' => 'site_builder.provision.manage'],
        '*' => ['view' => 'site_builder.catalog.view', 'manage' => 'site_builder.catalog.manage'],
    ],
    'marketing' => [
        'settings' => ['view' => 'marketing.site.view', 'manage' => 'marketing.site.manage'],
        'pages' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'blog' => ['view' => 'marketing.blog.view', 'manage' => 'marketing.blog.manage'],
        'magazine' => ['view' => 'marketing.blog.view', 'manage' => 'marketing.blog.manage'],
        'academy' => ['view' => 'marketing.blog.view', 'manage' => 'marketing.blog.manage'],
        'portfolio' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'faq' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'team' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'announcements' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'testimonials' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'downloads' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'services' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'service-categories' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'solutions' => ['view' => 'marketing.pages.view', 'manage' => 'marketing.pages.manage'],
        'media' => ['view' => 'marketing.media.view', 'manage' => 'marketing.media.manage'],
        '*' => ['view' => 'marketing.site.view', 'manage' => 'marketing.site.manage'],
    ],
];
