import type { LucideIcon } from 'lucide-react';
import {
  BarChart3,
  BookOpen,
  Box,
  Building2,
  Calendar,
  CalendarCheck,
  Calculator,
  CreditCard,
  Download,
  Factory,
  FileSearch,
  FileText,
  Folder,
  FolderKanban,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Image,
  Inbox,
  Key,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  LineChart,
  ListChecks,
  Megaphone,
  MessageSquare,
  Newspaper,
  Package,
  Palette,
  Phone,
  PlusCircle,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Layers,
  Store,
  Ticket,
  Timer,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
} from 'lucide-react';

/** Remix-style keys from the ERP registry map to Lucide icons (no Remix CSS). */
const ICON_MAP: Record<string, LucideIcon> = {
  'ri-home-4-line': LayoutDashboard,
  'ri-bar-chart-box-line': BarChart3,
  'ri-bar-chart-2-line': BarChart3,
  'ri-line-chart-line': LineChart,
  'ri-team-line': Users,
  'ri-group-line': Users,
  'ri-user-line': Users,
  'ri-user-star-line': Users,
  'ri-user-add-line': UserPlus,
  'ri-user-settings-line': Settings,
  'ri-wallet-3-line': Wallet,
  'ri-wallet-line': Wallet,
  'ri-customer-service-2-line': MessageSquare,
  'ri-customer-service-line': MessageSquare,
  'ri-folder-chart-line': FolderKanban,
  'ri-folder-2-line': FolderKanban,
  'ri-folder-line': Folder,
  'ri-archive-line': Warehouse,
  'ri-shopping-bag-line': ShoppingBag,
  'ri-shopping-cart-line': ShoppingCart,
  'ri-file-text-line': FileText,
  'ri-file-list-line': FileText,
  'ri-file-list-2-line': FileText,
  'ri-file-list-3-line': FileText,
  'ri-file-search-line': FileSearch,
  'ri-settings-3-line': Settings,
  'ri-settings-5-line': Settings,
  'ri-building-line': Building2,
  'ri-building-4-line': Building2,
  'ri-calendar-line': Calendar,
  'ri-calendar-check-line': CalendarCheck,
  'ri-calendar-event-line': Calendar,
  'ri-calendar-schedule-line': Calendar,
  'ri-box-3-line': Box,
  'ri-store-2-line': Store,
  'ri-message-2-line': MessageSquare,
  'ri-robot-2-line': MessageSquare,
  'ri-send-plane-line': Send,
  'ri-phone-line': Phone,
  'ri-draft-line': FileText,
  'ri-code-box-line': Package,
  'ri-contacts-book-line': Users,
  'ri-money-dollar-circle-line': Wallet,
  'ri-graduation-cap-line': GraduationCap,
  'ri-calculator-line': Calculator,
  'ri-bank-line': Building2,
  'ri-bank-card-line': CreditCard,
  'ri-exchange-dollar-line': Wallet,
  'ri-book-open-line': BookOpen,
  'ri-book-2-line': BookOpen,
  'ri-funds-line': LineChart,
  'ri-git-branch-line': GitBranch,
  'ri-discuss-line': MessageSquare,
  'ri-task-line': ListChecks,
  'ri-time-line': Timer,
  'ri-stack-line': Layers,
  'ri-inbox-archive-line': Inbox,
  'ri-inbox-unarchive-line': Inbox,
  'ri-service-line': Package,
  'ri-megaphone-line': Megaphone,
  'ri-dashboard-line': LayoutDashboard,
  'ri-list-check-2': ListChecks,
  'ri-hammer-line': Hammer,
  'ri-shield-check-line': ShieldCheck,
  'ri-layout-masonry-line': LayoutGrid,
  'ri-grid-line': LayoutGrid,
  'ri-global-line': Globe,
  'ri-add-circle-line': PlusCircle,
  'ri-add-box-line': PlusCircle,
  'ri-newspaper-line': Newspaper,
  'ri-image-line': Image,
  'ri-article-line': FileText,
  'ri-gallery-line': Image,
  'ri-question-line': Lightbulb,
  'ri-lightbulb-line': Lightbulb,
  'ri-chat-quote-line': MessageSquare,
  'ri-download-line': Download,
  'ri-palette-line': Palette,
  'ri-key-2-line': Key,
  'ri-server-line': Server,
  'ri-ticket-line': Ticket,
  'ri-factory-line': Factory,
};

export function moduleIcon(name?: string): LucideIcon {
  if (!name) return LayoutDashboard;
  return ICON_MAP[name] ?? LayoutDashboard;
}

export function renderIcon(Icon: LucideIcon, className?: string) {
  return <Icon className={className} />;
}
